/*
 * RegionValue.java
 *
 * Created on 25 June 2008, 11:10
 */
package com.ptoye.TestKiller;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  PToye
 */

public class RegionValue extends javax.swing.JDialog {

  static final long serialVersionUID = 1L;
  private Integer chosenValue = null;
  private SpinnerModel sm;
  private SpinnerNumberModel snm;

  /** Creates new form RegionValue
   * @param parent
   * @param min
   * @param max 
   */
  public RegionValue(java.awt.Frame parent, int min, int max) {
    super(parent, true);
    initComponents();
    setLocationRelativeTo(parent);
    sm = spnValue.getModel();
    if (sm instanceof SpinnerNumberModel) {
      InputMap im=getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
      ActionMap am=getRootPane().getActionMap();
      snm = (SpinnerNumberModel) sm;
      snm.setMinimum(min);
      snm.setMaximum(max);
      snm.setValue(min);
      getRootPane().setDefaultButton(btnOK);
      im.put(KeyStroke.getKeyStroke("ESCAPE"), "Cancel");
      im.put(KeyStroke.getKeyStroke("ENTER"), "OK");
      am.put("OK", new OKAction());
      am.put("Cancel", new CancelAction());
      
      this.setVisible(true);
    } else {
      System.exit(1);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {//GEN-BEGIN:initComponents

    jPanel1 = new javax.swing.JPanel();
    btnOK = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    spnValue = new javax.swing.JSpinner();

    FormListener formListener = new FormListener();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Set region value");
    setAlwaysOnTop(true);
    setFont(new java.awt.Font("SansSerif", 0, 12));
    setModal(true);
    setResizable(false);

    btnOK.setText("OK");
    btnOK.addActionListener(formListener);

    btnCancel.setText("Cancel");
    btnCancel.addActionListener(formListener);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnOK)
        .addGap(27, 27, 27)
        .addComponent(btnCancel)
        .addContainerGap())
    );

    jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOK});

    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnOK)
          .addComponent(btnCancel))
        .addContainerGap())
    );

    jLabel1.setText("Value for shape:");

    spnValue.setModel(new javax.swing.SpinnerNumberModel());

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(spnValue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(jLabel1)
          .addComponent(spnValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(18, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }

  // Code for dispatching events from components to event handlers.

  private class FormListener implements java.awt.event.ActionListener {
    FormListener() {}
    public void actionPerformed(java.awt.event.ActionEvent evt) {
      if (evt.getSource() == btnOK) {
        RegionValue.this.btnOKActionPerformed(evt);
      }
      else if (evt.getSource() == btnCancel) {
        RegionValue.this.btnCancelActionPerformed(evt);
      }
    }
  }//GEN-END:initComponents

private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
  Object o = snm.getValue();
  if (o instanceof Integer) {
    chosenValue = (Integer) o;
  } else {
    chosenValue = null;
  }
  this.setVisible(false);
}//GEN-LAST:event_btnOKActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
  chosenValue = null;
  this.setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

private class OKAction extends AbstractAction {
    @Override
  public void actionPerformed(ActionEvent e) {
    btnOKActionPerformed(null);
  }
}

private class CancelAction extends AbstractAction {
    @Override
  public void actionPerformed(ActionEvent e) {
    btnCancelActionPerformed(null);
  }
}

  public Integer getChosenValue() {
    return chosenValue;
  }
 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnOK;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSpinner spnValue;
  // End of variables declaration//GEN-END:variables
}
